name: release

on:
  repository_dispatch:
    types:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: papeloto/action-zip@v1
        with:
          files: package.json package-lock.json dist/
          dest: dist.zip
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - run: git push origin main
  merge:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Merge main back into dev
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          head_to_merge: main
          target_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
  publish_docs:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: npm ci
      - name: Build documentation
        env:
          NODE_ENV: production
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          cname: node-hypixel.zikeji.com